export interface CargoItem {
  id: string;
  name_fr: string;
  category: "baby" | "sport" | "travel" | "daily" | "pet";
  icon: string;
  volume_liters: number;
  length_cm: number;
  width_cm: number;
  height_cm: number;
  weight_kg: number;
  foldable: boolean;
  stackable: boolean;
}

export const CARGO_CATEGORIES = {
  baby: { label: "B\u00e9b\u00e9 & Enfants", icon: "\uD83D\uDC76" },
  sport: { label: "Sport & Loisirs", icon: "\uD83D\uDEB4" },
  travel: { label: "Voyage", icon: "\u2708\uFE0F" },
  daily: { label: "Quotidien", icon: "\uD83D\uDED2" },
  pet: { label: "Animaux", icon: "\uD83D\uDC15" },
} as const;

export const PRESET_CARGO_ITEMS: CargoItem[] = [
  // ─── B\u00e9b\u00e9 & Enfants ────
  {
    id: "stroller-compact",
    name_fr: "Poussette compacte (Yoyo, Pockit)",
    category: "baby",
    icon: "\uD83D\uDC76",
    volume_liters: 41,
    length_cm: 52, width_cm: 44, height_cm: 18,
    weight_kg: 6,
    foldable: true, stackable: false,
  },
  {
    id: "stroller-standard",
    name_fr: "Poussette standard (Bugaboo, Cybex)",
    category: "baby",
    icon: "\uD83D\uDC76",
    volume_liters: 100,
    length_cm: 90, width_cm: 45, height_cm: 25,
    weight_kg: 12,
    foldable: true, stackable: false,
  },
  {
    id: "stroller-double",
    name_fr: "Poussette double",
    category: "baby",
    icon: "\uD83D\uDC76",
    volume_liters: 200,
    length_cm: 110, width_cm: 75, height_cm: 40,
    weight_kg: 18,
    foldable: true, stackable: false,
  },
  {
    id: "infant-carrier",
    name_fr: "Coque b\u00e9b\u00e9 (0-13 kg)",
    category: "baby",
    icon: "\uD83C\uDF7C",
    volume_liters: 175,
    length_cm: 70, width_cm: 44, height_cm: 57,
    weight_kg: 4,
    foldable: false, stackable: false,
  },
  {
    id: "booster-seat",
    name_fr: "R\u00e9hausseur",
    category: "baby",
    icon: "\uD83E\uDE91",
    volume_liters: 32,
    length_cm: 40, width_cm: 36, height_cm: 22,
    weight_kg: 2,
    foldable: false, stackable: true,
  },
  {
    id: "diaper-bag",
    name_fr: "Sac \u00e0 langer",
    category: "baby",
    icon: "\uD83D\uDC5C",
    volume_liters: 32,
    length_cm: 45, width_cm: 35, height_cm: 20,
    weight_kg: 3,
    foldable: false, stackable: true,
  },
  {
    id: "playpen-travel",
    name_fr: "Lit parapluie",
    category: "baby",
    icon: "\uD83D\uDECF\uFE0F",
    volume_liters: 55,
    length_cm: 78, width_cm: 28, height_cm: 25,
    weight_kg: 10,
    foldable: true, stackable: false,
  },

  // ─── Sport & Loisirs ────
  {
    id: "bike-road",
    name_fr: "V\u00e9lo route (roue avant d\u00e9mont\u00e9e)",
    category: "sport",
    icon: "\uD83D\uDEB4",
    volume_liters: 700,
    length_cm: 170, width_cm: 55, height_cm: 75,
    weight_kg: 9,
    foldable: false, stackable: false,
  },
  {
    id: "bike-folding",
    name_fr: "V\u00e9lo pliant (Brompton)",
    category: "sport",
    icon: "\uD83D\uDEB2",
    volume_liters: 89,
    length_cm: 58, width_cm: 27, height_cm: 57,
    weight_kg: 12,
    foldable: true, stackable: false,
  },
  {
    id: "bike-kids",
    name_fr: "V\u00e9lo enfant (16 pouces)",
    category: "sport",
    icon: "\uD83D\uDEB4",
    volume_liters: 297,
    length_cm: 110, width_cm: 45, height_cm: 60,
    weight_kg: 8,
    foldable: false, stackable: false,
  },
  {
    id: "golf-bag",
    name_fr: "Sac de golf",
    category: "sport",
    icon: "\u26F3",
    volume_liters: 159,
    length_cm: 130, width_cm: 35, height_cm: 35,
    weight_kg: 12,
    foldable: false, stackable: false,
  },
  {
    id: "skis-pair",
    name_fr: "Paire de skis",
    category: "sport",
    icon: "\u26F7\uFE0F",
    volume_liters: 53,
    length_cm: 175, width_cm: 25, height_cm: 12,
    weight_kg: 5,
    foldable: false, stackable: true,
  },
  {
    id: "snowboard",
    name_fr: "Snowboard",
    category: "sport",
    icon: "\uD83C\uDFC2",
    volume_liters: 15,
    length_cm: 160, width_cm: 32, height_cm: 3,
    weight_kg: 4,
    foldable: false, stackable: true,
  },
  {
    id: "ski-boots",
    name_fr: "Chaussures de ski (paire)",
    category: "sport",
    icon: "\uD83E\uDD7E",
    volume_liters: 39,
    length_cm: 35, width_cm: 28, height_cm: 40,
    weight_kg: 4,
    foldable: false, stackable: false,
  },
  {
    id: "tent-4p",
    name_fr: "Tente 4 places",
    category: "sport",
    icon: "\u26FA",
    volume_liters: 29,
    length_cm: 60, width_cm: 22, height_cm: 22,
    weight_kg: 5,
    foldable: true, stackable: true,
  },
  {
    id: "cooler-36l",
    name_fr: "Glaci\u00e8re 36L",
    category: "sport",
    icon: "\uD83E\uDDCA",
    volume_liters: 77,
    length_cm: 55, width_cm: 35, height_cm: 40,
    weight_kg: 5,
    foldable: false, stackable: true,
  },

  // ─── Voyage ────
  {
    id: "suitcase-cabin",
    name_fr: "Valise cabine (55\u00d740\u00d720)",
    category: "travel",
    icon: "\uD83E\uDDF3",
    volume_liters: 44,
    length_cm: 55, width_cm: 40, height_cm: 20,
    weight_kg: 3,
    foldable: false, stackable: true,
  },
  {
    id: "suitcase-medium",
    name_fr: "Valise moyenne (65\u00d745\u00d725)",
    category: "travel",
    icon: "\uD83E\uDDF3",
    volume_liters: 73,
    length_cm: 65, width_cm: 45, height_cm: 25,
    weight_kg: 4,
    foldable: false, stackable: true,
  },
  {
    id: "suitcase-large",
    name_fr: "Grande valise (75\u00d750\u00d730)",
    category: "travel",
    icon: "\uD83E\uDDF3",
    volume_liters: 112,
    length_cm: 75, width_cm: 50, height_cm: 30,
    weight_kg: 5,
    foldable: false, stackable: true,
  },
  {
    id: "backpack-hiking",
    name_fr: "Sac \u00e0 dos rando 50L",
    category: "travel",
    icon: "\uD83C\uDF92",
    volume_liters: 61,
    length_cm: 70, width_cm: 35, height_cm: 25,
    weight_kg: 2,
    foldable: false, stackable: false,
  },
  {
    id: "duffel-bag",
    name_fr: "Sac de sport",
    category: "travel",
    icon: "\uD83D\uDC5C",
    volume_liters: 54,
    length_cm: 60, width_cm: 30, height_cm: 30,
    weight_kg: 1,
    foldable: true, stackable: true,
  },

  // ─── Quotidien ────
  {
    id: "grocery-weekly",
    name_fr: "Courses semaine (4 sacs)",
    category: "daily",
    icon: "\uD83D\uDED2",
    volume_liters: 80,
    length_cm: 50, width_cm: 40, height_cm: 40,
    weight_kg: 15,
    foldable: false, stackable: false,
  },
  {
    id: "ikea-flatpack-small",
    name_fr: "Carton IKEA petit (KALLAX)",
    category: "daily",
    icon: "\uD83D\uDCE6",
    volume_liters: 29,
    length_cm: 80, width_cm: 45, height_cm: 8,
    weight_kg: 15,
    foldable: false, stackable: true,
  },
  {
    id: "ikea-flatpack-large",
    name_fr: "Carton IKEA grand (PAX)",
    category: "daily",
    icon: "\uD83D\uDCE6",
    volume_liters: 150,
    length_cm: 230, width_cm: 65, height_cm: 10,
    weight_kg: 50,
    foldable: false, stackable: true,
  },
  {
    id: "moving-box",
    name_fr: "Carton d\u00e9m\u00e9nagement (60\u00d740\u00d740)",
    category: "daily",
    icon: "\uD83D\uDCE6",
    volume_liters: 96,
    length_cm: 60, width_cm: 40, height_cm: 40,
    weight_kg: 1,
    foldable: true, stackable: true,
  },

  // ─── Animaux ────
  {
    id: "dog-crate-large",
    name_fr: "Cage chien grande (Labrador)",
    category: "pet",
    icon: "\uD83D\uDC15",
    volume_liters: 585,
    length_cm: 107, width_cm: 71, height_cm: 77,
    weight_kg: 15,
    foldable: true, stackable: false,
  },
  {
    id: "dog-crate-medium",
    name_fr: "Cage chien moyenne (Beagle)",
    category: "pet",
    icon: "\uD83D\uDC15",
    volume_liters: 193,
    length_cm: 76, width_cm: 48, height_cm: 53,
    weight_kg: 10,
    foldable: true, stackable: false,
  },
  {
    id: "cat-carrier",
    name_fr: "Caisse de transport chat",
    category: "pet",
    icon: "\uD83D\uDC08",
    volume_liters: 69,
    length_cm: 55, width_cm: 36, height_cm: 35,
    weight_kg: 2,
    foldable: false, stackable: true,
  },
];
