import { createClient } from '@supabase/supabase-js';

const supabase = createClient(
  'https://gtixhrjeshkaobwxuvox.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0aXhocmplc2hrYW9id3h1dm94Iiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc2OTQyNzEyMCwiZXhwIjoyMDg1MDAzMTIwfQ.FpNyOQiUwcPAPCvpid-yQzdYYRKQxbGDYbln01YbRjM'
);

async function wtfIsGoingOn() {
  // Raw count
  const { count: totalCount } = await supabase
    .from('third_party_specs')
    .select('*', { count: 'exact', head: true });
  
  console.log(`Total rows in third_party_specs: ${totalCount}`);
  
  // Count by source
  const { data: bySrc } = await supabase
    .from('third_party_specs')
    .select('source');
  
  const srcCount: Record<string, number> = {};
  bySrc?.forEach(r => { srcCount[r.source] = (srcCount[r.source] || 0) + 1; });
  
  console.log('\nBy source:');
  Object.entries(srcCount).sort((a,b) => b[1] - a[1]).forEach(([s, c]) => console.log(`  ${s}: ${c}`));
  
  // Count Generated by spec_type
  const { data: byType } = await supabase
    .from('third_party_specs')
    .select('spec_type')
    .eq('source', 'Generated');
  
  const typeCount: Record<string, number> = {};
  byType?.forEach(r => { typeCount[r.spec_type] = (typeCount[r.spec_type] || 0) + 1; });
  
  console.log('\nGenerated by spec_type:');
  Object.entries(typeCount).sort((a,b) => b[1] - a[1]).forEach(([t, c]) => console.log(`  ${t}: ${c}`));
  
  // Unique generation_ids for Generated
  const { data: genIds } = await supabase
    .from('third_party_specs')
    .select('generation_id')
    .eq('source', 'Generated');
  
  const uniqueGens = new Set(genIds?.map(g => g.generation_id));
  console.log(`\nUnique generation_ids with Generated: ${uniqueGens.size}`);
  
  // Sample 5 random generation_ids from Generated
  const sample = [...uniqueGens].slice(0, 5);
  console.log('\nSample covered generation_ids:');
  sample.forEach(id => console.log(`  ${id}`));
  
  // Get 5 generation_ids that should exist but don't have Generated
  const { data: allGens } = await supabase.from('generations').select('id').limit(1000);
  const allGenSet = new Set(allGens?.map(g => g.id));
  const missing = [...allGenSet].filter(id => !uniqueGens.has(id)).slice(0, 5);
  
  console.log('\nSample MISSING generation_ids:');
  missing.forEach(id => console.log(`  ${id}`));
  
  // Try to find ANY spec for a missing one
  if (missing[0]) {
    const { data: anySpec, count } = await supabase
      .from('third_party_specs')
      .select('*', { count: 'exact' })
      .eq('generation_id', missing[0]);
    
    console.log(`\nSpecs for missing gen ${missing[0].substring(0,8)}...: ${count}`);
    if (anySpec?.length) {
      console.log('Sources:', [...new Set(anySpec.map(s => s.source))]);
    }
  }
}

wtfIsGoingOn();
